### ISSUE TITLE
Incompatibility with other dependencies

### ISSUE THREAD

**Issue by PINHOf** [andrey-ushakov/esc_pos_bluetooth#84]
My pubspec.yaml has the following dependencies:

```
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.6
  image_picker: ^0.8.0+3
  photo_view: ^0.11.1
  native_pdf_view: ^4.1.0
  printing: ^5.4.3
```
If I add `esc_pos_bluetooth: ^0.2.8` the console throws the following errors:

> Running "flutter pub get"...                 
> Because esc_pos_bluetooth >=0.2.8 depends on esc_pos_utils ^0.3.6 which depends on image ^2.1.4, esc_pos_bluetooth >=0.2.8 requires image ^2.1.4.
> 
> And because printing >=5.0.1 depends on image ^3.0.1, esc_pos_bluetooth >=0.2.8 is incompatible with printing >=5.0.1.
> 
> So, because [appName] depends on both printing ^5.4.3 and esc_pos_bluetooth ^0.2.8, version solving failed.
> pub get failed (1; So, because [appName] depends on both printing ^5.4.3 and esc_pos_bluetooth ^0.2.8, version solving failed.)
> exit code 1
